# Generated by Django 6.0.3 on 2026-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
