# Generated by Django 6.0.3 on 2026-03-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_about_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='default_slot_duration',
            field=models.PositiveIntegerField(default=15, help_text='Default slot duration in minutes'),
        ),
    ]
